### ISSUE TITLE
Medium paywall?

### ISSUE THREAD

**Issue by gingerbeardman** [maxbbraun/pisight#1]
Nice work in the project!

It's a shame the article pisight.camera points to is behind the Medium paywall. I had to use a Safari Private Window to read it.

**Comment by maxbbraun** [comment]
The domain [pisight.camera](https://pisight.camera) redirects to a link that [deliberately has no paywall](https://help.medium.com/hc/en-us/articles/360006543813-About-Friend-Links). It seems to work for most people, but I've had another person mention issues too. Maybe a bug on the Medium side.

**Comment by moorlag** [comment]
<img width="756" alt="scren" src="https://github.com/maxbbraun/pisight/assets/2832006/06add042-4833-4519-8f8f-82ee44823aa2">
Sadly it's no longer accessible. I've bought all the components, nice Christmas holiday project! Thanks @maxbbraun!

**Comment by maxbbraun** [comment]
Try [this link](https://debugger.medium.com/todays-webcams-are-boring-so-i-brought-back-a-classic-291cc7c94c76?sk=20bc3e039f6b39cf1df6cc4f825c8e64) instead. I've also updated the [pisight.camera](https://pisight.camera) redirect, but there might be a caching issue.
